// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id              int64  `json:"id"`
	Username        string `json:"name"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  string `json:"total_favorited"`
	WorkCount       int64  `json:"work_count"`
	FavoriteCount   int64  `json:"favorite_count"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResp struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResp struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserId     int64  `json:"user_id,omitempty"`
	Token      string `json:"token,omitempty"`
}

type UserInfoReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type UserInfoResp struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	User       User   `json:"user,omitempty"`
}

type FollowReq struct {
	Token      string `form:"token"`
	ToUserId   string `form:"to_user_id"`
	ActionType string `form:"action_type"`
}

type FollowResp struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type FollowListReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type FollowListResp struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list,omitempty"`
}

type FollowerListReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type FollowerListResp struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list,omitempty"`
}

type FriendListReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type FriendListResp struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list,omitempty"`
}
