// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"model_video/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/Video/FeedVideo/GetVideoList",
				Handler: GetVideoListHandler(serverCtx),
			},
		},
	)
}
