// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type Video struct {
	Id            int64  `json:"id,omitempty"`
	Author        User   `json:"author"`
	PlayUrl       string `json:"play_url,omitempty"`
	CoverUrl      string `json:"cover_url,omitempty"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	Title         string `json:"title,omitempty"`
	IsFavorite    bool   `json:"is_favorite"`
}

type User struct {
	Id              int64  `json:"id"`
	Username        string `json:"name"`
	FollowCount     int64  `json:"follow_count,omitempty"`
	FollowerCount   int64  `json:"follower_count,omitempty"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar,omitempty"`
	BackgroundImage string `json:"background_image,omitempty"`
	Signature       string `json:"signature,omitempty"`
	TotalFavorited  int64  `json:"total_favorited,omitempty"`
	WorkCount       int64  `json:"work_count,omitempty"`
	FavoriteCount   int64  `json:"favorite_count,omitempty"`
}

type FriendUser struct {
	User
	Message string `json:"message,omitempty"`
	MsgType int64  `json:"msgType"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type UserInfoReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type UserInfoResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	User       User   `json:"user"`
}

type FollowReq struct {
	Token      string `form:"token"`
	ToUserId   int64  `form:"to_user_id"`
	ActionType int32  `form:"action_type"`
}

type FollowResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
}

type FollowListReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FollowListResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list"`
}

type FollowerListReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FollowerListResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list"`
}

type FriendListReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FriendListResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list"`
}

type FeedResponse struct {
	Response
	VideoList []Video `json:"video_list,omitempty"`
	NextTime  int64   `json:"next_time"`
}

type FeedRequest struct {
	LatestTime int64  `json:"latest_time,optional"`
	Token      string `json:"token,optional"`
}

type PublishRequest struct {
	Token    string `form:"token,optional"`
	Title    string `form:"title,optional"`
	PlayUrl  string `form:"play_url,optional"`
	CoverUrl string `form:"cover_url,optional"`
}

type PublishResponse struct {
	Response
}

type PublishListRequest struct {
	Token  string `form:"token,optional"`
	UserId int64  `form:"user_id"`
}

type PublishListResponse struct {
	Response
	VideoList []Video `json:"video_list"`
}

type CommentListRequest struct {
	Token   string `form:"token,optional"`
	VideoId int64  `form:"video_id,omitempty"`
}

type Comment struct {
	Id         int64  `json:"id"`
	User       User   `json:"user"`
	Content    string `json:"content"`
	CreateDate string `json:"create_date"`
}

type CommentListResponse struct {
	StatusCode  int32     `json:"status_code"`
	StatusMsg   string    `json:"status_msg,optional"`
	CommentList []Comment `json:"comment_list,omitempty"`
}

type CommentActionRequest struct {
	Token       string `form:"token"`
	VideoId     int64  `form:"video_id"`
	ActionType  int32  `form:"action_type"`
	CommentText string `form:"comment_text,optional"`
	CommentId   int64  `form:"comment_id,optional"`
}

type CommentActionResponse struct {
	Response
	Comment *Comment `json:"comment"`
}

type FavoriteListRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token,optional"`
}

type FavoriteListResponse struct {
	Response
	VideoList []Video `json:"video_list"`
}

type FavoriteActionRequest struct {
	Token      string `form:"token,optional"`
	VideoId    int64  `form:"video_id"`
	ActionType int32  `form:"action_type"`
}

type FavoriteActionResponse struct {
	Response
}
